spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/ticketguru
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
    max-active: 10
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-test-query: SELECT 1
      data-source-properties:
        connectTimeout: 3000
        socketTimeout: 3000
    hibernate:
      ddl: update
  data:
    rest:
      basePath: /api

  flyway:
    schemas: ticketguru
    baseline-on-migrate: true
    validate-on-migrate: false #true to populate local DB
    table: info
    enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate: INFO
